networks:
  yuki_network:
    driver: bridge

services:
  db:
    build:
      context: ./postgres
      dockerfile: Dockerfile
    image: vinstp/yuki_buy_log:db
    container_name: yuki_db
    networks:
      - yuki_network
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: yukibuylog
    restart: unless-stopped

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: vinstp/yuki_buy_log:server
    container_name: yuki_server
    networks:
      - yuki_network
    environment:
      # Database connection
      DATABASE_URL: postgres://user:pass@db:5432/yukibuylog?sslmode=disable
      # Server port (internal container port)
      SERVER_PORT: "8080"
      # CORS origin - client domain
      CORS_ORIGIN: https://yuki.stepan-vinokurov-moscow.ru
    depends_on:
      - db
    ports:
      - "8080:8080"
    restart: unless-stopped

  client:
    build:
      context: ./clients
      dockerfile: Dockerfile
      args:
        # API URL - server endpoint accessible from browser
        # For Dokploy, this will be proxied through /api path
        VITE_API_URL: https://yuki.stepan-vinokurov-moscow.ru/api
    image: vinstp/yuki_buy_log:client
    container_name: yuki_client
    networks:
      - yuki_network
    depends_on:
      - server
    ports:
      - "8000:8000"
    restart: unless-stopped
