// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package database

import (
	"time"
	"yuki_buy_log/models"

	mock "github.com/stretchr/testify/mock"
)

// NewMockIDataBaseManager creates a new instance of MockIDataBaseManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIDataBaseManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIDataBaseManager {
	mock := &MockIDataBaseManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIDataBaseManager is an autogenerated mock type for the IDataBaseManager type
type MockIDataBaseManager struct {
	mock.Mock
}

type MockIDataBaseManager_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIDataBaseManager) EXPECT() *MockIDataBaseManager_Expecter {
	return &MockIDataBaseManager_Expecter{mock: &_m.Mock}
}

// AddPurchase provides a mock function for the type MockIDataBaseManager
func (_mock *MockIDataBaseManager) AddPurchase(purchase *models.Purchase) error {
	ret := _mock.Called(purchase)

	if len(ret) == 0 {
		panic("no return value specified for AddPurchase")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*models.Purchase) error); ok {
		r0 = returnFunc(purchase)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIDataBaseManager_AddPurchase_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddPurchase'
type MockIDataBaseManager_AddPurchase_Call struct {
	*mock.Call
}

// AddPurchase is a helper method to define mock.On call
//   - purchase *models.Purchase
func (_e *MockIDataBaseManager_Expecter) AddPurchase(purchase interface{}) *MockIDataBaseManager_AddPurchase_Call {
	return &MockIDataBaseManager_AddPurchase_Call{Call: _e.mock.On("AddPurchase", purchase)}
}

func (_c *MockIDataBaseManager_AddPurchase_Call) Run(run func(purchase *models.Purchase)) *MockIDataBaseManager_AddPurchase_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *models.Purchase
		if args[0] != nil {
			arg0 = args[0].(*models.Purchase)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIDataBaseManager_AddPurchase_Call) Return(err error) *MockIDataBaseManager_AddPurchase_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIDataBaseManager_AddPurchase_Call) RunAndReturn(run func(purchase *models.Purchase) error) *MockIDataBaseManager_AddPurchase_Call {
	_c.Call.Return(run)
	return _c
}

// AddUser provides a mock function for the type MockIDataBaseManager
func (_mock *MockIDataBaseManager) AddUser(user *models.User) error {
	ret := _mock.Called(user)

	if len(ret) == 0 {
		panic("no return value specified for AddUser")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*models.User) error); ok {
		r0 = returnFunc(user)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIDataBaseManager_AddUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddUser'
type MockIDataBaseManager_AddUser_Call struct {
	*mock.Call
}

// AddUser is a helper method to define mock.On call
//   - user *models.User
func (_e *MockIDataBaseManager_Expecter) AddUser(user interface{}) *MockIDataBaseManager_AddUser_Call {
	return &MockIDataBaseManager_AddUser_Call{Call: _e.mock.On("AddUser", user)}
}

func (_c *MockIDataBaseManager_AddUser_Call) Run(run func(user *models.User)) *MockIDataBaseManager_AddUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *models.User
		if args[0] != nil {
			arg0 = args[0].(*models.User)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIDataBaseManager_AddUser_Call) Return(err error) *MockIDataBaseManager_AddUser_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIDataBaseManager_AddUser_Call) RunAndReturn(run func(user *models.User) error) *MockIDataBaseManager_AddUser_Call {
	_c.Call.Return(run)
	return _c
}

// AddUserToGroup provides a mock function for the type MockIDataBaseManager
func (_mock *MockIDataBaseManager) AddUserToGroup(groupId models.GroupId, userId models.UserId, memberNumber int) error {
	ret := _mock.Called(groupId, userId, memberNumber)

	if len(ret) == 0 {
		panic("no return value specified for AddUserToGroup")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(models.GroupId, models.UserId, int) error); ok {
		r0 = returnFunc(groupId, userId, memberNumber)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIDataBaseManager_AddUserToGroup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddUserToGroup'
type MockIDataBaseManager_AddUserToGroup_Call struct {
	*mock.Call
}

// AddUserToGroup is a helper method to define mock.On call
//   - groupId models.GroupId
//   - userId models.UserId
//   - memberNumber int
func (_e *MockIDataBaseManager_Expecter) AddUserToGroup(groupId interface{}, userId interface{}, memberNumber interface{}) *MockIDataBaseManager_AddUserToGroup_Call {
	return &MockIDataBaseManager_AddUserToGroup_Call{Call: _e.mock.On("AddUserToGroup", groupId, userId, memberNumber)}
}

func (_c *MockIDataBaseManager_AddUserToGroup_Call) Run(run func(groupId models.GroupId, userId models.UserId, memberNumber int)) *MockIDataBaseManager_AddUserToGroup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 models.GroupId
		if args[0] != nil {
			arg0 = args[0].(models.GroupId)
		}
		var arg1 models.UserId
		if args[1] != nil {
			arg1 = args[1].(models.UserId)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockIDataBaseManager_AddUserToGroup_Call) Return(err error) *MockIDataBaseManager_AddUserToGroup_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIDataBaseManager_AddUserToGroup_Call) RunAndReturn(run func(groupId models.GroupId, userId models.UserId, memberNumber int) error) *MockIDataBaseManager_AddUserToGroup_Call {
	_c.Call.Return(run)
	return _c
}

// CreateInvite provides a mock function for the type MockIDataBaseManager
func (_mock *MockIDataBaseManager) CreateInvite(fromUserId models.UserId, toUserId models.UserId) (models.InviteId, error) {
	ret := _mock.Called(fromUserId, toUserId)

	if len(ret) == 0 {
		panic("no return value specified for CreateInvite")
	}

	var r0 models.InviteId
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(models.UserId, models.UserId) (models.InviteId, error)); ok {
		return returnFunc(fromUserId, toUserId)
	}
	if returnFunc, ok := ret.Get(0).(func(models.UserId, models.UserId) models.InviteId); ok {
		r0 = returnFunc(fromUserId, toUserId)
	} else {
		r0 = ret.Get(0).(models.InviteId)
	}
	if returnFunc, ok := ret.Get(1).(func(models.UserId, models.UserId) error); ok {
		r1 = returnFunc(fromUserId, toUserId)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIDataBaseManager_CreateInvite_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateInvite'
type MockIDataBaseManager_CreateInvite_Call struct {
	*mock.Call
}

// CreateInvite is a helper method to define mock.On call
//   - fromUserId models.UserId
//   - toUserId models.UserId
func (_e *MockIDataBaseManager_Expecter) CreateInvite(fromUserId interface{}, toUserId interface{}) *MockIDataBaseManager_CreateInvite_Call {
	return &MockIDataBaseManager_CreateInvite_Call{Call: _e.mock.On("CreateInvite", fromUserId, toUserId)}
}

func (_c *MockIDataBaseManager_CreateInvite_Call) Run(run func(fromUserId models.UserId, toUserId models.UserId)) *MockIDataBaseManager_CreateInvite_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 models.UserId
		if args[0] != nil {
			arg0 = args[0].(models.UserId)
		}
		var arg1 models.UserId
		if args[1] != nil {
			arg1 = args[1].(models.UserId)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIDataBaseManager_CreateInvite_Call) Return(inviteId models.InviteId, err error) *MockIDataBaseManager_CreateInvite_Call {
	_c.Call.Return(inviteId, err)
	return _c
}

func (_c *MockIDataBaseManager_CreateInvite_Call) RunAndReturn(run func(fromUserId models.UserId, toUserId models.UserId) (models.InviteId, error)) *MockIDataBaseManager_CreateInvite_Call {
	_c.Call.Return(run)
	return _c
}

// CreateNewGroup provides a mock function for the type MockIDataBaseManager
func (_mock *MockIDataBaseManager) CreateNewGroup(userId models.UserId) (models.GroupId, error) {
	ret := _mock.Called(userId)

	if len(ret) == 0 {
		panic("no return value specified for CreateNewGroup")
	}

	var r0 models.GroupId
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(models.UserId) (models.GroupId, error)); ok {
		return returnFunc(userId)
	}
	if returnFunc, ok := ret.Get(0).(func(models.UserId) models.GroupId); ok {
		r0 = returnFunc(userId)
	} else {
		r0 = ret.Get(0).(models.GroupId)
	}
	if returnFunc, ok := ret.Get(1).(func(models.UserId) error); ok {
		r1 = returnFunc(userId)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIDataBaseManager_CreateNewGroup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateNewGroup'
type MockIDataBaseManager_CreateNewGroup_Call struct {
	*mock.Call
}

// CreateNewGroup is a helper method to define mock.On call
//   - userId models.UserId
func (_e *MockIDataBaseManager_Expecter) CreateNewGroup(userId interface{}) *MockIDataBaseManager_CreateNewGroup_Call {
	return &MockIDataBaseManager_CreateNewGroup_Call{Call: _e.mock.On("CreateNewGroup", userId)}
}

func (_c *MockIDataBaseManager_CreateNewGroup_Call) Run(run func(userId models.UserId)) *MockIDataBaseManager_CreateNewGroup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 models.UserId
		if args[0] != nil {
			arg0 = args[0].(models.UserId)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIDataBaseManager_CreateNewGroup_Call) Return(groupId models.GroupId, err error) *MockIDataBaseManager_CreateNewGroup_Call {
	_c.Call.Return(groupId, err)
	return _c
}

func (_c *MockIDataBaseManager_CreateNewGroup_Call) RunAndReturn(run func(userId models.UserId) (models.GroupId, error)) *MockIDataBaseManager_CreateNewGroup_Call {
	_c.Call.Return(run)
	return _c
}

// CreateProduct provides a mock function for the type MockIDataBaseManager
func (_mock *MockIDataBaseManager) CreateProduct(product *models.Product) error {
	ret := _mock.Called(product)

	if len(ret) == 0 {
		panic("no return value specified for CreateProduct")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*models.Product) error); ok {
		r0 = returnFunc(product)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIDataBaseManager_CreateProduct_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateProduct'
type MockIDataBaseManager_CreateProduct_Call struct {
	*mock.Call
}

// CreateProduct is a helper method to define mock.On call
//   - product *models.Product
func (_e *MockIDataBaseManager_Expecter) CreateProduct(product interface{}) *MockIDataBaseManager_CreateProduct_Call {
	return &MockIDataBaseManager_CreateProduct_Call{Call: _e.mock.On("CreateProduct", product)}
}

func (_c *MockIDataBaseManager_CreateProduct_Call) Run(run func(product *models.Product)) *MockIDataBaseManager_CreateProduct_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *models.Product
		if args[0] != nil {
			arg0 = args[0].(*models.Product)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIDataBaseManager_CreateProduct_Call) Return(err error) *MockIDataBaseManager_CreateProduct_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIDataBaseManager_CreateProduct_Call) RunAndReturn(run func(product *models.Product) error) *MockIDataBaseManager_CreateProduct_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteGroupMembersByGroupId provides a mock function for the type MockIDataBaseManager
func (_mock *MockIDataBaseManager) DeleteGroupMembersByGroupId(id models.GroupId) error {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteGroupMembersByGroupId")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(models.GroupId) error); ok {
		r0 = returnFunc(id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIDataBaseManager_DeleteGroupMembersByGroupId_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteGroupMembersByGroupId'
type MockIDataBaseManager_DeleteGroupMembersByGroupId_Call struct {
	*mock.Call
}

// DeleteGroupMembersByGroupId is a helper method to define mock.On call
//   - id models.GroupId
func (_e *MockIDataBaseManager_Expecter) DeleteGroupMembersByGroupId(id interface{}) *MockIDataBaseManager_DeleteGroupMembersByGroupId_Call {
	return &MockIDataBaseManager_DeleteGroupMembersByGroupId_Call{Call: _e.mock.On("DeleteGroupMembersByGroupId", id)}
}

func (_c *MockIDataBaseManager_DeleteGroupMembersByGroupId_Call) Run(run func(id models.GroupId)) *MockIDataBaseManager_DeleteGroupMembersByGroupId_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 models.GroupId
		if args[0] != nil {
			arg0 = args[0].(models.GroupId)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIDataBaseManager_DeleteGroupMembersByGroupId_Call) Return(err error) *MockIDataBaseManager_DeleteGroupMembersByGroupId_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIDataBaseManager_DeleteGroupMembersByGroupId_Call) RunAndReturn(run func(id models.GroupId) error) *MockIDataBaseManager_DeleteGroupMembersByGroupId_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteInvitesBetweenUsers provides a mock function for the type MockIDataBaseManager
func (_mock *MockIDataBaseManager) DeleteInvitesBetweenUsers(userId1 models.UserId, userId2 models.UserId) error {
	ret := _mock.Called(userId1, userId2)

	if len(ret) == 0 {
		panic("no return value specified for DeleteInvitesBetweenUsers")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(models.UserId, models.UserId) error); ok {
		r0 = returnFunc(userId1, userId2)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIDataBaseManager_DeleteInvitesBetweenUsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteInvitesBetweenUsers'
type MockIDataBaseManager_DeleteInvitesBetweenUsers_Call struct {
	*mock.Call
}

// DeleteInvitesBetweenUsers is a helper method to define mock.On call
//   - userId1 models.UserId
//   - userId2 models.UserId
func (_e *MockIDataBaseManager_Expecter) DeleteInvitesBetweenUsers(userId1 interface{}, userId2 interface{}) *MockIDataBaseManager_DeleteInvitesBetweenUsers_Call {
	return &MockIDataBaseManager_DeleteInvitesBetweenUsers_Call{Call: _e.mock.On("DeleteInvitesBetweenUsers", userId1, userId2)}
}

func (_c *MockIDataBaseManager_DeleteInvitesBetweenUsers_Call) Run(run func(userId1 models.UserId, userId2 models.UserId)) *MockIDataBaseManager_DeleteInvitesBetweenUsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 models.UserId
		if args[0] != nil {
			arg0 = args[0].(models.UserId)
		}
		var arg1 models.UserId
		if args[1] != nil {
			arg1 = args[1].(models.UserId)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIDataBaseManager_DeleteInvitesBetweenUsers_Call) Return(err error) *MockIDataBaseManager_DeleteInvitesBetweenUsers_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIDataBaseManager_DeleteInvitesBetweenUsers_Call) RunAndReturn(run func(userId1 models.UserId, userId2 models.UserId) error) *MockIDataBaseManager_DeleteInvitesBetweenUsers_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteOldInvites provides a mock function for the type MockIDataBaseManager
func (_mock *MockIDataBaseManager) DeleteOldInvites(cutoffTime time.Time) (int64, error) {
	ret := _mock.Called(cutoffTime)

	if len(ret) == 0 {
		panic("no return value specified for DeleteOldInvites")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(time.Time) (int64, error)); ok {
		return returnFunc(cutoffTime)
	}
	if returnFunc, ok := ret.Get(0).(func(time.Time) int64); ok {
		r0 = returnFunc(cutoffTime)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(time.Time) error); ok {
		r1 = returnFunc(cutoffTime)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIDataBaseManager_DeleteOldInvites_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteOldInvites'
type MockIDataBaseManager_DeleteOldInvites_Call struct {
	*mock.Call
}

// DeleteOldInvites is a helper method to define mock.On call
//   - cutoffTime time.Time
func (_e *MockIDataBaseManager_Expecter) DeleteOldInvites(cutoffTime interface{}) *MockIDataBaseManager_DeleteOldInvites_Call {
	return &MockIDataBaseManager_DeleteOldInvites_Call{Call: _e.mock.On("DeleteOldInvites", cutoffTime)}
}

func (_c *MockIDataBaseManager_DeleteOldInvites_Call) Run(run func(cutoffTime time.Time)) *MockIDataBaseManager_DeleteOldInvites_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 time.Time
		if args[0] != nil {
			arg0 = args[0].(time.Time)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIDataBaseManager_DeleteOldInvites_Call) Return(n int64, err error) *MockIDataBaseManager_DeleteOldInvites_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockIDataBaseManager_DeleteOldInvites_Call) RunAndReturn(run func(cutoffTime time.Time) (int64, error)) *MockIDataBaseManager_DeleteOldInvites_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteProduct provides a mock function for the type MockIDataBaseManager
func (_mock *MockIDataBaseManager) DeleteProduct(id models.ProductId, userId models.UserId) error {
	ret := _mock.Called(id, userId)

	if len(ret) == 0 {
		panic("no return value specified for DeleteProduct")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(models.ProductId, models.UserId) error); ok {
		r0 = returnFunc(id, userId)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIDataBaseManager_DeleteProduct_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteProduct'
type MockIDataBaseManager_DeleteProduct_Call struct {
	*mock.Call
}

// DeleteProduct is a helper method to define mock.On call
//   - id models.ProductId
//   - userId models.UserId
func (_e *MockIDataBaseManager_Expecter) DeleteProduct(id interface{}, userId interface{}) *MockIDataBaseManager_DeleteProduct_Call {
	return &MockIDataBaseManager_DeleteProduct_Call{Call: _e.mock.On("DeleteProduct", id, userId)}
}

func (_c *MockIDataBaseManager_DeleteProduct_Call) Run(run func(id models.ProductId, userId models.UserId)) *MockIDataBaseManager_DeleteProduct_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 models.ProductId
		if args[0] != nil {
			arg0 = args[0].(models.ProductId)
		}
		var arg1 models.UserId
		if args[1] != nil {
			arg1 = args[1].(models.UserId)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIDataBaseManager_DeleteProduct_Call) Return(err error) *MockIDataBaseManager_DeleteProduct_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIDataBaseManager_DeleteProduct_Call) RunAndReturn(run func(id models.ProductId, userId models.UserId) error) *MockIDataBaseManager_DeleteProduct_Call {
	_c.Call.Return(run)
	return _c
}

// DeletePurchase provides a mock function for the type MockIDataBaseManager
func (_mock *MockIDataBaseManager) DeletePurchase(purchaseId models.PurchaseId, userId models.UserId) error {
	ret := _mock.Called(purchaseId, userId)

	if len(ret) == 0 {
		panic("no return value specified for DeletePurchase")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(models.PurchaseId, models.UserId) error); ok {
		r0 = returnFunc(purchaseId, userId)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIDataBaseManager_DeletePurchase_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeletePurchase'
type MockIDataBaseManager_DeletePurchase_Call struct {
	*mock.Call
}

// DeletePurchase is a helper method to define mock.On call
//   - purchaseId models.PurchaseId
//   - userId models.UserId
func (_e *MockIDataBaseManager_Expecter) DeletePurchase(purchaseId interface{}, userId interface{}) *MockIDataBaseManager_DeletePurchase_Call {
	return &MockIDataBaseManager_DeletePurchase_Call{Call: _e.mock.On("DeletePurchase", purchaseId, userId)}
}

func (_c *MockIDataBaseManager_DeletePurchase_Call) Run(run func(purchaseId models.PurchaseId, userId models.UserId)) *MockIDataBaseManager_DeletePurchase_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 models.PurchaseId
		if args[0] != nil {
			arg0 = args[0].(models.PurchaseId)
		}
		var arg1 models.UserId
		if args[1] != nil {
			arg1 = args[1].(models.UserId)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIDataBaseManager_DeletePurchase_Call) Return(err error) *MockIDataBaseManager_DeletePurchase_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIDataBaseManager_DeletePurchase_Call) RunAndReturn(run func(purchaseId models.PurchaseId, userId models.UserId) error) *MockIDataBaseManager_DeletePurchase_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteUser provides a mock function for the type MockIDataBaseManager
func (_mock *MockIDataBaseManager) DeleteUser(userId models.UserId) error {
	ret := _mock.Called(userId)

	if len(ret) == 0 {
		panic("no return value specified for DeleteUser")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(models.UserId) error); ok {
		r0 = returnFunc(userId)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIDataBaseManager_DeleteUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteUser'
type MockIDataBaseManager_DeleteUser_Call struct {
	*mock.Call
}

// DeleteUser is a helper method to define mock.On call
//   - userId models.UserId
func (_e *MockIDataBaseManager_Expecter) DeleteUser(userId interface{}) *MockIDataBaseManager_DeleteUser_Call {
	return &MockIDataBaseManager_DeleteUser_Call{Call: _e.mock.On("DeleteUser", userId)}
}

func (_c *MockIDataBaseManager_DeleteUser_Call) Run(run func(userId models.UserId)) *MockIDataBaseManager_DeleteUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 models.UserId
		if args[0] != nil {
			arg0 = args[0].(models.UserId)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIDataBaseManager_DeleteUser_Call) Return(err error) *MockIDataBaseManager_DeleteUser_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIDataBaseManager_DeleteUser_Call) RunAndReturn(run func(userId models.UserId) error) *MockIDataBaseManager_DeleteUser_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteUserFromGroup provides a mock function for the type MockIDataBaseManager
func (_mock *MockIDataBaseManager) DeleteUserFromGroup(userId models.UserId) error {
	ret := _mock.Called(userId)

	if len(ret) == 0 {
		panic("no return value specified for DeleteUserFromGroup")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(models.UserId) error); ok {
		r0 = returnFunc(userId)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIDataBaseManager_DeleteUserFromGroup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteUserFromGroup'
type MockIDataBaseManager_DeleteUserFromGroup_Call struct {
	*mock.Call
}

// DeleteUserFromGroup is a helper method to define mock.On call
//   - userId models.UserId
func (_e *MockIDataBaseManager_Expecter) DeleteUserFromGroup(userId interface{}) *MockIDataBaseManager_DeleteUserFromGroup_Call {
	return &MockIDataBaseManager_DeleteUserFromGroup_Call{Call: _e.mock.On("DeleteUserFromGroup", userId)}
}

func (_c *MockIDataBaseManager_DeleteUserFromGroup_Call) Run(run func(userId models.UserId)) *MockIDataBaseManager_DeleteUserFromGroup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 models.UserId
		if args[0] != nil {
			arg0 = args[0].(models.UserId)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIDataBaseManager_DeleteUserFromGroup_Call) Return(err error) *MockIDataBaseManager_DeleteUserFromGroup_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIDataBaseManager_DeleteUserFromGroup_Call) RunAndReturn(run func(userId models.UserId) error) *MockIDataBaseManager_DeleteUserFromGroup_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllGroupMembers provides a mock function for the type MockIDataBaseManager
func (_mock *MockIDataBaseManager) GetAllGroupMembers() ([]models.GroupMember, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAllGroupMembers")
	}

	var r0 []models.GroupMember
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([]models.GroupMember, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []models.GroupMember); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.GroupMember)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIDataBaseManager_GetAllGroupMembers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllGroupMembers'
type MockIDataBaseManager_GetAllGroupMembers_Call struct {
	*mock.Call
}

// GetAllGroupMembers is a helper method to define mock.On call
func (_e *MockIDataBaseManager_Expecter) GetAllGroupMembers() *MockIDataBaseManager_GetAllGroupMembers_Call {
	return &MockIDataBaseManager_GetAllGroupMembers_Call{Call: _e.mock.On("GetAllGroupMembers")}
}

func (_c *MockIDataBaseManager_GetAllGroupMembers_Call) Run(run func()) *MockIDataBaseManager_GetAllGroupMembers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIDataBaseManager_GetAllGroupMembers_Call) Return(result []models.GroupMember, err error) *MockIDataBaseManager_GetAllGroupMembers_Call {
	_c.Call.Return(result, err)
	return _c
}

func (_c *MockIDataBaseManager_GetAllGroupMembers_Call) RunAndReturn(run func() ([]models.GroupMember, error)) *MockIDataBaseManager_GetAllGroupMembers_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllInvites provides a mock function for the type MockIDataBaseManager
func (_mock *MockIDataBaseManager) GetAllInvites() ([]models.Invite, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAllInvites")
	}

	var r0 []models.Invite
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([]models.Invite, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []models.Invite); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Invite)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIDataBaseManager_GetAllInvites_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllInvites'
type MockIDataBaseManager_GetAllInvites_Call struct {
	*mock.Call
}

// GetAllInvites is a helper method to define mock.On call
func (_e *MockIDataBaseManager_Expecter) GetAllInvites() *MockIDataBaseManager_GetAllInvites_Call {
	return &MockIDataBaseManager_GetAllInvites_Call{Call: _e.mock.On("GetAllInvites")}
}

func (_c *MockIDataBaseManager_GetAllInvites_Call) Run(run func()) *MockIDataBaseManager_GetAllInvites_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIDataBaseManager_GetAllInvites_Call) Return(invites []models.Invite, err error) *MockIDataBaseManager_GetAllInvites_Call {
	_c.Call.Return(invites, err)
	return _c
}

func (_c *MockIDataBaseManager_GetAllInvites_Call) RunAndReturn(run func() ([]models.Invite, error)) *MockIDataBaseManager_GetAllInvites_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllProducts provides a mock function for the type MockIDataBaseManager
func (_mock *MockIDataBaseManager) GetAllProducts() ([]models.Product, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAllProducts")
	}

	var r0 []models.Product
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([]models.Product, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []models.Product); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Product)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIDataBaseManager_GetAllProducts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllProducts'
type MockIDataBaseManager_GetAllProducts_Call struct {
	*mock.Call
}

// GetAllProducts is a helper method to define mock.On call
func (_e *MockIDataBaseManager_Expecter) GetAllProducts() *MockIDataBaseManager_GetAllProducts_Call {
	return &MockIDataBaseManager_GetAllProducts_Call{Call: _e.mock.On("GetAllProducts")}
}

func (_c *MockIDataBaseManager_GetAllProducts_Call) Run(run func()) *MockIDataBaseManager_GetAllProducts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIDataBaseManager_GetAllProducts_Call) Return(products []models.Product, err error) *MockIDataBaseManager_GetAllProducts_Call {
	_c.Call.Return(products, err)
	return _c
}

func (_c *MockIDataBaseManager_GetAllProducts_Call) RunAndReturn(run func() ([]models.Product, error)) *MockIDataBaseManager_GetAllProducts_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllPurchases provides a mock function for the type MockIDataBaseManager
func (_mock *MockIDataBaseManager) GetAllPurchases() ([]models.Purchase, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAllPurchases")
	}

	var r0 []models.Purchase
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([]models.Purchase, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []models.Purchase); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Purchase)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIDataBaseManager_GetAllPurchases_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllPurchases'
type MockIDataBaseManager_GetAllPurchases_Call struct {
	*mock.Call
}

// GetAllPurchases is a helper method to define mock.On call
func (_e *MockIDataBaseManager_Expecter) GetAllPurchases() *MockIDataBaseManager_GetAllPurchases_Call {
	return &MockIDataBaseManager_GetAllPurchases_Call{Call: _e.mock.On("GetAllPurchases")}
}

func (_c *MockIDataBaseManager_GetAllPurchases_Call) Run(run func()) *MockIDataBaseManager_GetAllPurchases_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIDataBaseManager_GetAllPurchases_Call) Return(purchases []models.Purchase, err error) *MockIDataBaseManager_GetAllPurchases_Call {
	_c.Call.Return(purchases, err)
	return _c
}

func (_c *MockIDataBaseManager_GetAllPurchases_Call) RunAndReturn(run func() ([]models.Purchase, error)) *MockIDataBaseManager_GetAllPurchases_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllUsers provides a mock function for the type MockIDataBaseManager
func (_mock *MockIDataBaseManager) GetAllUsers() ([]models.User, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAllUsers")
	}

	var r0 []models.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([]models.User, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []models.User); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIDataBaseManager_GetAllUsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllUsers'
type MockIDataBaseManager_GetAllUsers_Call struct {
	*mock.Call
}

// GetAllUsers is a helper method to define mock.On call
func (_e *MockIDataBaseManager_Expecter) GetAllUsers() *MockIDataBaseManager_GetAllUsers_Call {
	return &MockIDataBaseManager_GetAllUsers_Call{Call: _e.mock.On("GetAllUsers")}
}

func (_c *MockIDataBaseManager_GetAllUsers_Call) Run(run func()) *MockIDataBaseManager_GetAllUsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIDataBaseManager_GetAllUsers_Call) Return(users []models.User, err error) *MockIDataBaseManager_GetAllUsers_Call {
	_c.Call.Return(users, err)
	return _c
}

func (_c *MockIDataBaseManager_GetAllUsers_Call) RunAndReturn(run func() ([]models.User, error)) *MockIDataBaseManager_GetAllUsers_Call {
	_c.Call.Return(run)
	return _c
}

// GetGroupMembersByGroupId provides a mock function for the type MockIDataBaseManager
func (_mock *MockIDataBaseManager) GetGroupMembersByGroupId(id models.GroupId) ([]models.GroupMember, error) {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetGroupMembersByGroupId")
	}

	var r0 []models.GroupMember
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(models.GroupId) ([]models.GroupMember, error)); ok {
		return returnFunc(id)
	}
	if returnFunc, ok := ret.Get(0).(func(models.GroupId) []models.GroupMember); ok {
		r0 = returnFunc(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.GroupMember)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(models.GroupId) error); ok {
		r1 = returnFunc(id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIDataBaseManager_GetGroupMembersByGroupId_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetGroupMembersByGroupId'
type MockIDataBaseManager_GetGroupMembersByGroupId_Call struct {
	*mock.Call
}

// GetGroupMembersByGroupId is a helper method to define mock.On call
//   - id models.GroupId
func (_e *MockIDataBaseManager_Expecter) GetGroupMembersByGroupId(id interface{}) *MockIDataBaseManager_GetGroupMembersByGroupId_Call {
	return &MockIDataBaseManager_GetGroupMembersByGroupId_Call{Call: _e.mock.On("GetGroupMembersByGroupId", id)}
}

func (_c *MockIDataBaseManager_GetGroupMembersByGroupId_Call) Run(run func(id models.GroupId)) *MockIDataBaseManager_GetGroupMembersByGroupId_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 models.GroupId
		if args[0] != nil {
			arg0 = args[0].(models.GroupId)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIDataBaseManager_GetGroupMembersByGroupId_Call) Return(result []models.GroupMember, err error) *MockIDataBaseManager_GetGroupMembersByGroupId_Call {
	_c.Call.Return(result, err)
	return _c
}

func (_c *MockIDataBaseManager_GetGroupMembersByGroupId_Call) RunAndReturn(run func(id models.GroupId) ([]models.GroupMember, error)) *MockIDataBaseManager_GetGroupMembersByGroupId_Call {
	_c.Call.Return(run)
	return _c
}

// GetIncomingInvites provides a mock function for the type MockIDataBaseManager
func (_mock *MockIDataBaseManager) GetIncomingInvites(userId models.UserId) ([]models.Invite, error) {
	ret := _mock.Called(userId)

	if len(ret) == 0 {
		panic("no return value specified for GetIncomingInvites")
	}

	var r0 []models.Invite
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(models.UserId) ([]models.Invite, error)); ok {
		return returnFunc(userId)
	}
	if returnFunc, ok := ret.Get(0).(func(models.UserId) []models.Invite); ok {
		r0 = returnFunc(userId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Invite)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(models.UserId) error); ok {
		r1 = returnFunc(userId)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIDataBaseManager_GetIncomingInvites_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetIncomingInvites'
type MockIDataBaseManager_GetIncomingInvites_Call struct {
	*mock.Call
}

// GetIncomingInvites is a helper method to define mock.On call
//   - userId models.UserId
func (_e *MockIDataBaseManager_Expecter) GetIncomingInvites(userId interface{}) *MockIDataBaseManager_GetIncomingInvites_Call {
	return &MockIDataBaseManager_GetIncomingInvites_Call{Call: _e.mock.On("GetIncomingInvites", userId)}
}

func (_c *MockIDataBaseManager_GetIncomingInvites_Call) Run(run func(userId models.UserId)) *MockIDataBaseManager_GetIncomingInvites_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 models.UserId
		if args[0] != nil {
			arg0 = args[0].(models.UserId)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIDataBaseManager_GetIncomingInvites_Call) Return(invites []models.Invite, err error) *MockIDataBaseManager_GetIncomingInvites_Call {
	_c.Call.Return(invites, err)
	return _c
}

func (_c *MockIDataBaseManager_GetIncomingInvites_Call) RunAndReturn(run func(userId models.UserId) ([]models.Invite, error)) *MockIDataBaseManager_GetIncomingInvites_Call {
	_c.Call.Return(run)
	return _c
}

// GetInvite provides a mock function for the type MockIDataBaseManager
func (_mock *MockIDataBaseManager) GetInvite(fromUserId models.UserId, toUserId models.UserId) (models.Invite, error) {
	ret := _mock.Called(fromUserId, toUserId)

	if len(ret) == 0 {
		panic("no return value specified for GetInvite")
	}

	var r0 models.Invite
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(models.UserId, models.UserId) (models.Invite, error)); ok {
		return returnFunc(fromUserId, toUserId)
	}
	if returnFunc, ok := ret.Get(0).(func(models.UserId, models.UserId) models.Invite); ok {
		r0 = returnFunc(fromUserId, toUserId)
	} else {
		r0 = ret.Get(0).(models.Invite)
	}
	if returnFunc, ok := ret.Get(1).(func(models.UserId, models.UserId) error); ok {
		r1 = returnFunc(fromUserId, toUserId)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIDataBaseManager_GetInvite_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetInvite'
type MockIDataBaseManager_GetInvite_Call struct {
	*mock.Call
}

// GetInvite is a helper method to define mock.On call
//   - fromUserId models.UserId
//   - toUserId models.UserId
func (_e *MockIDataBaseManager_Expecter) GetInvite(fromUserId interface{}, toUserId interface{}) *MockIDataBaseManager_GetInvite_Call {
	return &MockIDataBaseManager_GetInvite_Call{Call: _e.mock.On("GetInvite", fromUserId, toUserId)}
}

func (_c *MockIDataBaseManager_GetInvite_Call) Run(run func(fromUserId models.UserId, toUserId models.UserId)) *MockIDataBaseManager_GetInvite_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 models.UserId
		if args[0] != nil {
			arg0 = args[0].(models.UserId)
		}
		var arg1 models.UserId
		if args[1] != nil {
			arg1 = args[1].(models.UserId)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIDataBaseManager_GetInvite_Call) Return(invite models.Invite, err error) *MockIDataBaseManager_GetInvite_Call {
	_c.Call.Return(invite, err)
	return _c
}

func (_c *MockIDataBaseManager_GetInvite_Call) RunAndReturn(run func(fromUserId models.UserId, toUserId models.UserId) (models.Invite, error)) *MockIDataBaseManager_GetInvite_Call {
	_c.Call.Return(run)
	return _c
}

// GetInvitesFromUser provides a mock function for the type MockIDataBaseManager
func (_mock *MockIDataBaseManager) GetInvitesFromUser(fromUserId models.InviteId) ([]models.Invite, error) {
	ret := _mock.Called(fromUserId)

	if len(ret) == 0 {
		panic("no return value specified for GetInvitesFromUser")
	}

	var r0 []models.Invite
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(models.InviteId) ([]models.Invite, error)); ok {
		return returnFunc(fromUserId)
	}
	if returnFunc, ok := ret.Get(0).(func(models.InviteId) []models.Invite); ok {
		r0 = returnFunc(fromUserId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Invite)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(models.InviteId) error); ok {
		r1 = returnFunc(fromUserId)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIDataBaseManager_GetInvitesFromUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetInvitesFromUser'
type MockIDataBaseManager_GetInvitesFromUser_Call struct {
	*mock.Call
}

// GetInvitesFromUser is a helper method to define mock.On call
//   - fromUserId models.InviteId
func (_e *MockIDataBaseManager_Expecter) GetInvitesFromUser(fromUserId interface{}) *MockIDataBaseManager_GetInvitesFromUser_Call {
	return &MockIDataBaseManager_GetInvitesFromUser_Call{Call: _e.mock.On("GetInvitesFromUser", fromUserId)}
}

func (_c *MockIDataBaseManager_GetInvitesFromUser_Call) Run(run func(fromUserId models.InviteId)) *MockIDataBaseManager_GetInvitesFromUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 models.InviteId
		if args[0] != nil {
			arg0 = args[0].(models.InviteId)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIDataBaseManager_GetInvitesFromUser_Call) Return(invites []models.Invite, err error) *MockIDataBaseManager_GetInvitesFromUser_Call {
	_c.Call.Return(invites, err)
	return _c
}

func (_c *MockIDataBaseManager_GetInvitesFromUser_Call) RunAndReturn(run func(fromUserId models.InviteId) ([]models.Invite, error)) *MockIDataBaseManager_GetInvitesFromUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetInvitesToUser provides a mock function for the type MockIDataBaseManager
func (_mock *MockIDataBaseManager) GetInvitesToUser(toUserId models.UserId) ([]models.Invite, error) {
	ret := _mock.Called(toUserId)

	if len(ret) == 0 {
		panic("no return value specified for GetInvitesToUser")
	}

	var r0 []models.Invite
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(models.UserId) ([]models.Invite, error)); ok {
		return returnFunc(toUserId)
	}
	if returnFunc, ok := ret.Get(0).(func(models.UserId) []models.Invite); ok {
		r0 = returnFunc(toUserId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Invite)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(models.UserId) error); ok {
		r1 = returnFunc(toUserId)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIDataBaseManager_GetInvitesToUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetInvitesToUser'
type MockIDataBaseManager_GetInvitesToUser_Call struct {
	*mock.Call
}

// GetInvitesToUser is a helper method to define mock.On call
//   - toUserId models.UserId
func (_e *MockIDataBaseManager_Expecter) GetInvitesToUser(toUserId interface{}) *MockIDataBaseManager_GetInvitesToUser_Call {
	return &MockIDataBaseManager_GetInvitesToUser_Call{Call: _e.mock.On("GetInvitesToUser", toUserId)}
}

func (_c *MockIDataBaseManager_GetInvitesToUser_Call) Run(run func(toUserId models.UserId)) *MockIDataBaseManager_GetInvitesToUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 models.UserId
		if args[0] != nil {
			arg0 = args[0].(models.UserId)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIDataBaseManager_GetInvitesToUser_Call) Return(invites []models.Invite, err error) *MockIDataBaseManager_GetInvitesToUser_Call {
	_c.Call.Return(invites, err)
	return _c
}

func (_c *MockIDataBaseManager_GetInvitesToUser_Call) RunAndReturn(run func(toUserId models.UserId) ([]models.Invite, error)) *MockIDataBaseManager_GetInvitesToUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetProductById provides a mock function for the type MockIDataBaseManager
func (_mock *MockIDataBaseManager) GetProductById(id models.ProductId) (*models.Product, error) {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetProductById")
	}

	var r0 *models.Product
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(models.ProductId) (*models.Product, error)); ok {
		return returnFunc(id)
	}
	if returnFunc, ok := ret.Get(0).(func(models.ProductId) *models.Product); ok {
		r0 = returnFunc(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Product)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(models.ProductId) error); ok {
		r1 = returnFunc(id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIDataBaseManager_GetProductById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProductById'
type MockIDataBaseManager_GetProductById_Call struct {
	*mock.Call
}

// GetProductById is a helper method to define mock.On call
//   - id models.ProductId
func (_e *MockIDataBaseManager_Expecter) GetProductById(id interface{}) *MockIDataBaseManager_GetProductById_Call {
	return &MockIDataBaseManager_GetProductById_Call{Call: _e.mock.On("GetProductById", id)}
}

func (_c *MockIDataBaseManager_GetProductById_Call) Run(run func(id models.ProductId)) *MockIDataBaseManager_GetProductById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 models.ProductId
		if args[0] != nil {
			arg0 = args[0].(models.ProductId)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIDataBaseManager_GetProductById_Call) Return(product *models.Product, err error) *MockIDataBaseManager_GetProductById_Call {
	_c.Call.Return(product, err)
	return _c
}

func (_c *MockIDataBaseManager_GetProductById_Call) RunAndReturn(run func(id models.ProductId) (*models.Product, error)) *MockIDataBaseManager_GetProductById_Call {
	_c.Call.Return(run)
	return _c
}

// GetPurchasesByUserIds provides a mock function for the type MockIDataBaseManager
func (_mock *MockIDataBaseManager) GetPurchasesByUserIds(userIds []models.UserId) ([]models.Purchase, error) {
	ret := _mock.Called(userIds)

	if len(ret) == 0 {
		panic("no return value specified for GetPurchasesByUserIds")
	}

	var r0 []models.Purchase
	var r1 error
	if returnFunc, ok := ret.Get(0).(func([]models.UserId) ([]models.Purchase, error)); ok {
		return returnFunc(userIds)
	}
	if returnFunc, ok := ret.Get(0).(func([]models.UserId) []models.Purchase); ok {
		r0 = returnFunc(userIds)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Purchase)
		}
	}
	if returnFunc, ok := ret.Get(1).(func([]models.UserId) error); ok {
		r1 = returnFunc(userIds)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIDataBaseManager_GetPurchasesByUserIds_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPurchasesByUserIds'
type MockIDataBaseManager_GetPurchasesByUserIds_Call struct {
	*mock.Call
}

// GetPurchasesByUserIds is a helper method to define mock.On call
//   - userIds []models.UserId
func (_e *MockIDataBaseManager_Expecter) GetPurchasesByUserIds(userIds interface{}) *MockIDataBaseManager_GetPurchasesByUserIds_Call {
	return &MockIDataBaseManager_GetPurchasesByUserIds_Call{Call: _e.mock.On("GetPurchasesByUserIds", userIds)}
}

func (_c *MockIDataBaseManager_GetPurchasesByUserIds_Call) Run(run func(userIds []models.UserId)) *MockIDataBaseManager_GetPurchasesByUserIds_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []models.UserId
		if args[0] != nil {
			arg0 = args[0].([]models.UserId)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIDataBaseManager_GetPurchasesByUserIds_Call) Return(purchases []models.Purchase, err error) *MockIDataBaseManager_GetPurchasesByUserIds_Call {
	_c.Call.Return(purchases, err)
	return _c
}

func (_c *MockIDataBaseManager_GetPurchasesByUserIds_Call) RunAndReturn(run func(userIds []models.UserId) ([]models.Purchase, error)) *MockIDataBaseManager_GetPurchasesByUserIds_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserById provides a mock function for the type MockIDataBaseManager
func (_mock *MockIDataBaseManager) GetUserById(id *models.UserId) (*models.User, error) {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetUserById")
	}

	var r0 *models.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*models.UserId) (*models.User, error)); ok {
		return returnFunc(id)
	}
	if returnFunc, ok := ret.Get(0).(func(*models.UserId) *models.User); ok {
		r0 = returnFunc(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*models.UserId) error); ok {
		r1 = returnFunc(id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIDataBaseManager_GetUserById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserById'
type MockIDataBaseManager_GetUserById_Call struct {
	*mock.Call
}

// GetUserById is a helper method to define mock.On call
//   - id *models.UserId
func (_e *MockIDataBaseManager_Expecter) GetUserById(id interface{}) *MockIDataBaseManager_GetUserById_Call {
	return &MockIDataBaseManager_GetUserById_Call{Call: _e.mock.On("GetUserById", id)}
}

func (_c *MockIDataBaseManager_GetUserById_Call) Run(run func(id *models.UserId)) *MockIDataBaseManager_GetUserById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *models.UserId
		if args[0] != nil {
			arg0 = args[0].(*models.UserId)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIDataBaseManager_GetUserById_Call) Return(user *models.User, err error) *MockIDataBaseManager_GetUserById_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockIDataBaseManager_GetUserById_Call) RunAndReturn(run func(id *models.UserId) (*models.User, error)) *MockIDataBaseManager_GetUserById_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserByLogin provides a mock function for the type MockIDataBaseManager
func (_mock *MockIDataBaseManager) GetUserByLogin(login string) (*models.User, error) {
	ret := _mock.Called(login)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByLogin")
	}

	var r0 *models.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*models.User, error)); ok {
		return returnFunc(login)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *models.User); ok {
		r0 = returnFunc(login)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(login)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIDataBaseManager_GetUserByLogin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByLogin'
type MockIDataBaseManager_GetUserByLogin_Call struct {
	*mock.Call
}

// GetUserByLogin is a helper method to define mock.On call
//   - login string
func (_e *MockIDataBaseManager_Expecter) GetUserByLogin(login interface{}) *MockIDataBaseManager_GetUserByLogin_Call {
	return &MockIDataBaseManager_GetUserByLogin_Call{Call: _e.mock.On("GetUserByLogin", login)}
}

func (_c *MockIDataBaseManager_GetUserByLogin_Call) Run(run func(login string)) *MockIDataBaseManager_GetUserByLogin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIDataBaseManager_GetUserByLogin_Call) Return(user *models.User, err error) *MockIDataBaseManager_GetUserByLogin_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockIDataBaseManager_GetUserByLogin_Call) RunAndReturn(run func(login string) (*models.User, error)) *MockIDataBaseManager_GetUserByLogin_Call {
	_c.Call.Return(run)
	return _c
}

// GetUsersByGroupId provides a mock function for the type MockIDataBaseManager
func (_mock *MockIDataBaseManager) GetUsersByGroupId(id *models.GroupId) ([]models.User, error) {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetUsersByGroupId")
	}

	var r0 []models.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*models.GroupId) ([]models.User, error)); ok {
		return returnFunc(id)
	}
	if returnFunc, ok := ret.Get(0).(func(*models.GroupId) []models.User); ok {
		r0 = returnFunc(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*models.GroupId) error); ok {
		r1 = returnFunc(id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIDataBaseManager_GetUsersByGroupId_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUsersByGroupId'
type MockIDataBaseManager_GetUsersByGroupId_Call struct {
	*mock.Call
}

// GetUsersByGroupId is a helper method to define mock.On call
//   - id *models.GroupId
func (_e *MockIDataBaseManager_Expecter) GetUsersByGroupId(id interface{}) *MockIDataBaseManager_GetUsersByGroupId_Call {
	return &MockIDataBaseManager_GetUsersByGroupId_Call{Call: _e.mock.On("GetUsersByGroupId", id)}
}

func (_c *MockIDataBaseManager_GetUsersByGroupId_Call) Run(run func(id *models.GroupId)) *MockIDataBaseManager_GetUsersByGroupId_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *models.GroupId
		if args[0] != nil {
			arg0 = args[0].(*models.GroupId)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIDataBaseManager_GetUsersByGroupId_Call) Return(users []models.User, err error) *MockIDataBaseManager_GetUsersByGroupId_Call {
	_c.Call.Return(users, err)
	return _c
}

func (_c *MockIDataBaseManager_GetUsersByGroupId_Call) RunAndReturn(run func(id *models.GroupId) ([]models.User, error)) *MockIDataBaseManager_GetUsersByGroupId_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateGroupMember provides a mock function for the type MockIDataBaseManager
func (_mock *MockIDataBaseManager) UpdateGroupMember(groupMember *models.GroupMember) error {
	ret := _mock.Called(groupMember)

	if len(ret) == 0 {
		panic("no return value specified for UpdateGroupMember")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*models.GroupMember) error); ok {
		r0 = returnFunc(groupMember)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIDataBaseManager_UpdateGroupMember_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateGroupMember'
type MockIDataBaseManager_UpdateGroupMember_Call struct {
	*mock.Call
}

// UpdateGroupMember is a helper method to define mock.On call
//   - groupMember *models.GroupMember
func (_e *MockIDataBaseManager_Expecter) UpdateGroupMember(groupMember interface{}) *MockIDataBaseManager_UpdateGroupMember_Call {
	return &MockIDataBaseManager_UpdateGroupMember_Call{Call: _e.mock.On("UpdateGroupMember", groupMember)}
}

func (_c *MockIDataBaseManager_UpdateGroupMember_Call) Run(run func(groupMember *models.GroupMember)) *MockIDataBaseManager_UpdateGroupMember_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *models.GroupMember
		if args[0] != nil {
			arg0 = args[0].(*models.GroupMember)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIDataBaseManager_UpdateGroupMember_Call) Return(err error) *MockIDataBaseManager_UpdateGroupMember_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIDataBaseManager_UpdateGroupMember_Call) RunAndReturn(run func(groupMember *models.GroupMember) error) *MockIDataBaseManager_UpdateGroupMember_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateProduct provides a mock function for the type MockIDataBaseManager
func (_mock *MockIDataBaseManager) UpdateProduct(product *models.Product) error {
	ret := _mock.Called(product)

	if len(ret) == 0 {
		panic("no return value specified for UpdateProduct")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*models.Product) error); ok {
		r0 = returnFunc(product)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIDataBaseManager_UpdateProduct_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateProduct'
type MockIDataBaseManager_UpdateProduct_Call struct {
	*mock.Call
}

// UpdateProduct is a helper method to define mock.On call
//   - product *models.Product
func (_e *MockIDataBaseManager_Expecter) UpdateProduct(product interface{}) *MockIDataBaseManager_UpdateProduct_Call {
	return &MockIDataBaseManager_UpdateProduct_Call{Call: _e.mock.On("UpdateProduct", product)}
}

func (_c *MockIDataBaseManager_UpdateProduct_Call) Run(run func(product *models.Product)) *MockIDataBaseManager_UpdateProduct_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *models.Product
		if args[0] != nil {
			arg0 = args[0].(*models.Product)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIDataBaseManager_UpdateProduct_Call) Return(err error) *MockIDataBaseManager_UpdateProduct_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIDataBaseManager_UpdateProduct_Call) RunAndReturn(run func(product *models.Product) error) *MockIDataBaseManager_UpdateProduct_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateUser provides a mock function for the type MockIDataBaseManager
func (_mock *MockIDataBaseManager) UpdateUser(user *models.User) error {
	ret := _mock.Called(user)

	if len(ret) == 0 {
		panic("no return value specified for UpdateUser")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*models.User) error); ok {
		r0 = returnFunc(user)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIDataBaseManager_UpdateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateUser'
type MockIDataBaseManager_UpdateUser_Call struct {
	*mock.Call
}

// UpdateUser is a helper method to define mock.On call
//   - user *models.User
func (_e *MockIDataBaseManager_Expecter) UpdateUser(user interface{}) *MockIDataBaseManager_UpdateUser_Call {
	return &MockIDataBaseManager_UpdateUser_Call{Call: _e.mock.On("UpdateUser", user)}
}

func (_c *MockIDataBaseManager_UpdateUser_Call) Run(run func(user *models.User)) *MockIDataBaseManager_UpdateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *models.User
		if args[0] != nil {
			arg0 = args[0].(*models.User)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIDataBaseManager_UpdateUser_Call) Return(err error) *MockIDataBaseManager_UpdateUser_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIDataBaseManager_UpdateUser_Call) RunAndReturn(run func(user *models.User) error) *MockIDataBaseManager_UpdateUser_Call {
	_c.Call.Return(run)
	return _c
}
