// Code generated by MockGen. DO NOT EDIT.
// Source: database/database.go
//
// Generated by this command:
//
//	mockgen -source=database/database.go -destination=mocks/mock_database.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"
	time "time"
	models "yuki_buy_log/models"

	gomock "go.uber.org/mock/gomock"
)

// MockIDataBaseManager is a mock of IDataBaseManager interface.
type MockIDataBaseManager struct {
	ctrl     *gomock.Controller
	recorder *MockIDataBaseManagerMockRecorder
	isgomock struct{}
}

// MockIDataBaseManagerMockRecorder is the mock recorder for MockIDataBaseManager.
type MockIDataBaseManagerMockRecorder struct {
	mock *MockIDataBaseManager
}

// NewMockIDataBaseManager creates a new mock instance.
func NewMockIDataBaseManager(ctrl *gomock.Controller) *MockIDataBaseManager {
	mock := &MockIDataBaseManager{ctrl: ctrl}
	mock.recorder = &MockIDataBaseManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIDataBaseManager) EXPECT() *MockIDataBaseManagerMockRecorder {
	return m.recorder
}

// AddPurchase mocks base method.
func (m *MockIDataBaseManager) AddPurchase(purchase *models.Purchase) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddPurchase", purchase)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddPurchase indicates an expected call of AddPurchase.
func (mr *MockIDataBaseManagerMockRecorder) AddPurchase(purchase any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddPurchase", reflect.TypeOf((*MockIDataBaseManager)(nil).AddPurchase), purchase)
}

// AddUser mocks base method.
func (m *MockIDataBaseManager) AddUser(user *models.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddUser", user)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddUser indicates an expected call of AddUser.
func (mr *MockIDataBaseManagerMockRecorder) AddUser(user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddUser", reflect.TypeOf((*MockIDataBaseManager)(nil).AddUser), user)
}

// AddUserToGroup mocks base method.
func (m *MockIDataBaseManager) AddUserToGroup(groupId models.GroupId, userId models.UserId, memberNumber int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddUserToGroup", groupId, userId, memberNumber)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddUserToGroup indicates an expected call of AddUserToGroup.
func (mr *MockIDataBaseManagerMockRecorder) AddUserToGroup(groupId, userId, memberNumber any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddUserToGroup", reflect.TypeOf((*MockIDataBaseManager)(nil).AddUserToGroup), groupId, userId, memberNumber)
}

// CreateInvite mocks base method.
func (m *MockIDataBaseManager) CreateInvite(fromUserId, toUserId models.UserId) (models.InviteId, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateInvite", fromUserId, toUserId)
	ret0, _ := ret[0].(models.InviteId)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateInvite indicates an expected call of CreateInvite.
func (mr *MockIDataBaseManagerMockRecorder) CreateInvite(fromUserId, toUserId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateInvite", reflect.TypeOf((*MockIDataBaseManager)(nil).CreateInvite), fromUserId, toUserId)
}

// CreateNewGroup mocks base method.
func (m *MockIDataBaseManager) CreateNewGroup(userId models.UserId) (models.GroupId, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateNewGroup", userId)
	ret0, _ := ret[0].(models.GroupId)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateNewGroup indicates an expected call of CreateNewGroup.
func (mr *MockIDataBaseManagerMockRecorder) CreateNewGroup(userId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateNewGroup", reflect.TypeOf((*MockIDataBaseManager)(nil).CreateNewGroup), userId)
}

// CreateProduct mocks base method.
func (m *MockIDataBaseManager) CreateProduct(product *models.Product) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateProduct", product)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateProduct indicates an expected call of CreateProduct.
func (mr *MockIDataBaseManagerMockRecorder) CreateProduct(product any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateProduct", reflect.TypeOf((*MockIDataBaseManager)(nil).CreateProduct), product)
}

// DeleteGroupMembersByGroupId mocks base method.
func (m *MockIDataBaseManager) DeleteGroupMembersByGroupId(id models.GroupId) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteGroupMembersByGroupId", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteGroupMembersByGroupId indicates an expected call of DeleteGroupMembersByGroupId.
func (mr *MockIDataBaseManagerMockRecorder) DeleteGroupMembersByGroupId(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteGroupMembersByGroupId", reflect.TypeOf((*MockIDataBaseManager)(nil).DeleteGroupMembersByGroupId), id)
}

// DeleteInvitesBetweenUsers mocks base method.
func (m *MockIDataBaseManager) DeleteInvitesBetweenUsers(userId1, userId2 models.UserId) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteInvitesBetweenUsers", userId1, userId2)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteInvitesBetweenUsers indicates an expected call of DeleteInvitesBetweenUsers.
func (mr *MockIDataBaseManagerMockRecorder) DeleteInvitesBetweenUsers(userId1, userId2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteInvitesBetweenUsers", reflect.TypeOf((*MockIDataBaseManager)(nil).DeleteInvitesBetweenUsers), userId1, userId2)
}

// DeleteOldInvites mocks base method.
func (m *MockIDataBaseManager) DeleteOldInvites(cutoffTime time.Time) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteOldInvites", cutoffTime)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteOldInvites indicates an expected call of DeleteOldInvites.
func (mr *MockIDataBaseManagerMockRecorder) DeleteOldInvites(cutoffTime any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteOldInvites", reflect.TypeOf((*MockIDataBaseManager)(nil).DeleteOldInvites), cutoffTime)
}

// DeleteProduct mocks base method.
func (m *MockIDataBaseManager) DeleteProduct(id models.ProductId, userId models.UserId) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteProduct", id, userId)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteProduct indicates an expected call of DeleteProduct.
func (mr *MockIDataBaseManagerMockRecorder) DeleteProduct(id, userId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteProduct", reflect.TypeOf((*MockIDataBaseManager)(nil).DeleteProduct), id, userId)
}

// DeletePurchase mocks base method.
func (m *MockIDataBaseManager) DeletePurchase(purchaseId models.PurchaseId, userId models.UserId) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeletePurchase", purchaseId, userId)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeletePurchase indicates an expected call of DeletePurchase.
func (mr *MockIDataBaseManagerMockRecorder) DeletePurchase(purchaseId, userId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeletePurchase", reflect.TypeOf((*MockIDataBaseManager)(nil).DeletePurchase), purchaseId, userId)
}

// DeleteUser mocks base method.
func (m *MockIDataBaseManager) DeleteUser(userId models.UserId) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteUser", userId)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteUser indicates an expected call of DeleteUser.
func (mr *MockIDataBaseManagerMockRecorder) DeleteUser(userId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUser", reflect.TypeOf((*MockIDataBaseManager)(nil).DeleteUser), userId)
}

// DeleteUserFromGroup mocks base method.
func (m *MockIDataBaseManager) DeleteUserFromGroup(userId models.UserId) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteUserFromGroup", userId)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteUserFromGroup indicates an expected call of DeleteUserFromGroup.
func (mr *MockIDataBaseManagerMockRecorder) DeleteUserFromGroup(userId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUserFromGroup", reflect.TypeOf((*MockIDataBaseManager)(nil).DeleteUserFromGroup), userId)
}

// GetAllGroupMembers mocks base method.
func (m *MockIDataBaseManager) GetAllGroupMembers() ([]models.GroupMember, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllGroupMembers")
	ret0, _ := ret[0].([]models.GroupMember)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllGroupMembers indicates an expected call of GetAllGroupMembers.
func (mr *MockIDataBaseManagerMockRecorder) GetAllGroupMembers() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllGroupMembers", reflect.TypeOf((*MockIDataBaseManager)(nil).GetAllGroupMembers))
}

// GetAllInvites mocks base method.
func (m *MockIDataBaseManager) GetAllInvites() ([]models.Invite, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllInvites")
	ret0, _ := ret[0].([]models.Invite)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllInvites indicates an expected call of GetAllInvites.
func (mr *MockIDataBaseManagerMockRecorder) GetAllInvites() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllInvites", reflect.TypeOf((*MockIDataBaseManager)(nil).GetAllInvites))
}

// GetAllProducts mocks base method.
func (m *MockIDataBaseManager) GetAllProducts() ([]models.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllProducts")
	ret0, _ := ret[0].([]models.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllProducts indicates an expected call of GetAllProducts.
func (mr *MockIDataBaseManagerMockRecorder) GetAllProducts() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllProducts", reflect.TypeOf((*MockIDataBaseManager)(nil).GetAllProducts))
}

// GetAllPurchases mocks base method.
func (m *MockIDataBaseManager) GetAllPurchases() ([]models.Purchase, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllPurchases")
	ret0, _ := ret[0].([]models.Purchase)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllPurchases indicates an expected call of GetAllPurchases.
func (mr *MockIDataBaseManagerMockRecorder) GetAllPurchases() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllPurchases", reflect.TypeOf((*MockIDataBaseManager)(nil).GetAllPurchases))
}

// GetAllUsers mocks base method.
func (m *MockIDataBaseManager) GetAllUsers() ([]models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllUsers")
	ret0, _ := ret[0].([]models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllUsers indicates an expected call of GetAllUsers.
func (mr *MockIDataBaseManagerMockRecorder) GetAllUsers() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllUsers", reflect.TypeOf((*MockIDataBaseManager)(nil).GetAllUsers))
}

// GetGroupMembersByGroupId mocks base method.
func (m *MockIDataBaseManager) GetGroupMembersByGroupId(id models.GroupId) ([]models.GroupMember, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGroupMembersByGroupId", id)
	ret0, _ := ret[0].([]models.GroupMember)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGroupMembersByGroupId indicates an expected call of GetGroupMembersByGroupId.
func (mr *MockIDataBaseManagerMockRecorder) GetGroupMembersByGroupId(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGroupMembersByGroupId", reflect.TypeOf((*MockIDataBaseManager)(nil).GetGroupMembersByGroupId), id)
}

// GetIncomingInvites mocks base method.
func (m *MockIDataBaseManager) GetIncomingInvites(userId models.UserId) ([]models.Invite, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIncomingInvites", userId)
	ret0, _ := ret[0].([]models.Invite)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetIncomingInvites indicates an expected call of GetIncomingInvites.
func (mr *MockIDataBaseManagerMockRecorder) GetIncomingInvites(userId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIncomingInvites", reflect.TypeOf((*MockIDataBaseManager)(nil).GetIncomingInvites), userId)
}

// GetInvite mocks base method.
func (m *MockIDataBaseManager) GetInvite(fromUserId, toUserId models.UserId) (models.Invite, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetInvite", fromUserId, toUserId)
	ret0, _ := ret[0].(models.Invite)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetInvite indicates an expected call of GetInvite.
func (mr *MockIDataBaseManagerMockRecorder) GetInvite(fromUserId, toUserId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetInvite", reflect.TypeOf((*MockIDataBaseManager)(nil).GetInvite), fromUserId, toUserId)
}

// GetInvitesFromUser mocks base method.
func (m *MockIDataBaseManager) GetInvitesFromUser(fromUserId models.InviteId) ([]models.Invite, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetInvitesFromUser", fromUserId)
	ret0, _ := ret[0].([]models.Invite)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetInvitesFromUser indicates an expected call of GetInvitesFromUser.
func (mr *MockIDataBaseManagerMockRecorder) GetInvitesFromUser(fromUserId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetInvitesFromUser", reflect.TypeOf((*MockIDataBaseManager)(nil).GetInvitesFromUser), fromUserId)
}

// GetInvitesToUser mocks base method.
func (m *MockIDataBaseManager) GetInvitesToUser(toUserId models.UserId) ([]models.Invite, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetInvitesToUser", toUserId)
	ret0, _ := ret[0].([]models.Invite)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetInvitesToUser indicates an expected call of GetInvitesToUser.
func (mr *MockIDataBaseManagerMockRecorder) GetInvitesToUser(toUserId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetInvitesToUser", reflect.TypeOf((*MockIDataBaseManager)(nil).GetInvitesToUser), toUserId)
}

// GetProductById mocks base method.
func (m *MockIDataBaseManager) GetProductById(id models.ProductId) (*models.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProductById", id)
	ret0, _ := ret[0].(*models.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProductById indicates an expected call of GetProductById.
func (mr *MockIDataBaseManagerMockRecorder) GetProductById(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProductById", reflect.TypeOf((*MockIDataBaseManager)(nil).GetProductById), id)
}

// GetPurchasesByUserIds mocks base method.
func (m *MockIDataBaseManager) GetPurchasesByUserIds(userIds []models.UserId) ([]models.Purchase, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPurchasesByUserIds", userIds)
	ret0, _ := ret[0].([]models.Purchase)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPurchasesByUserIds indicates an expected call of GetPurchasesByUserIds.
func (mr *MockIDataBaseManagerMockRecorder) GetPurchasesByUserIds(userIds any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPurchasesByUserIds", reflect.TypeOf((*MockIDataBaseManager)(nil).GetPurchasesByUserIds), userIds)
}

// GetUserById mocks base method.
func (m *MockIDataBaseManager) GetUserById(id *models.UserId) (*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserById", id)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserById indicates an expected call of GetUserById.
func (mr *MockIDataBaseManagerMockRecorder) GetUserById(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserById", reflect.TypeOf((*MockIDataBaseManager)(nil).GetUserById), id)
}

// GetUserByLogin mocks base method.
func (m *MockIDataBaseManager) GetUserByLogin(login string) (*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByLogin", login)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByLogin indicates an expected call of GetUserByLogin.
func (mr *MockIDataBaseManagerMockRecorder) GetUserByLogin(login any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByLogin", reflect.TypeOf((*MockIDataBaseManager)(nil).GetUserByLogin), login)
}

// GetUsersByGroupId mocks base method.
func (m *MockIDataBaseManager) GetUsersByGroupId(id *models.GroupId) ([]models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUsersByGroupId", id)
	ret0, _ := ret[0].([]models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUsersByGroupId indicates an expected call of GetUsersByGroupId.
func (mr *MockIDataBaseManagerMockRecorder) GetUsersByGroupId(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUsersByGroupId", reflect.TypeOf((*MockIDataBaseManager)(nil).GetUsersByGroupId), id)
}

// UpdateGroupMember mocks base method.
func (m *MockIDataBaseManager) UpdateGroupMember(groupMember *models.GroupMember) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateGroupMember", groupMember)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateGroupMember indicates an expected call of UpdateGroupMember.
func (mr *MockIDataBaseManagerMockRecorder) UpdateGroupMember(groupMember any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateGroupMember", reflect.TypeOf((*MockIDataBaseManager)(nil).UpdateGroupMember), groupMember)
}

// UpdateProduct mocks base method.
func (m *MockIDataBaseManager) UpdateProduct(product *models.Product) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateProduct", product)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateProduct indicates an expected call of UpdateProduct.
func (mr *MockIDataBaseManagerMockRecorder) UpdateProduct(product any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateProduct", reflect.TypeOf((*MockIDataBaseManager)(nil).UpdateProduct), product)
}

// UpdateUser mocks base method.
func (m *MockIDataBaseManager) UpdateUser(user *models.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUser", user)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateUser indicates an expected call of UpdateUser.
func (mr *MockIDataBaseManagerMockRecorder) UpdateUser(user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUser", reflect.TypeOf((*MockIDataBaseManager)(nil).UpdateUser), user)
}
