name: Integration tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  integration:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Docker layers - server
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache-server
          key: ${{ runner.os }}-buildx-server-${{ hashFiles('server/**') }}
          restore-keys: |
            ${{ runner.os }}-buildx-server-

      - name: Cache Docker layers - tests
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache-tests
          key: ${{ runner.os }}-buildx-tests-${{ hashFiles('integration_tests/**') }}
          restore-keys: |
            ${{ runner.os }}-buildx-tests-

      - name: Build and cache server image
        uses: docker/build-push-action@v5
        with:
          context: ./server
          file: ./server/Dockerfile
          tags: yuki_buy_log:server-test
          load: true
          cache-from: |
            type=local,src=/tmp/.buildx-cache-server
          cache-to: type=local,dest=/tmp/.buildx-cache-server-new,mode=max

      - name: Build and cache test image
        uses: docker/build-push-action@v5
        with:
          context: ./integration_tests
          file: ./integration_tests/Dockerfile
          tags: yuki_buy_log:integration-tests
          load: true
          cache-from: |
            type=local,src=/tmp/.buildx-cache-tests
          cache-to: type=local,dest=/tmp/.buildx-cache-tests-new,mode=max

      - name: Run integration tests
        run: |
          docker compose -f integration-tests.yml up \
            --abort-on-container-exit \
            --exit-code-from integration-tests

      - name: Show logs on failure
        if: failure()
        run: |
          echo "=== Server logs ==="
          docker compose -f integration-tests.yml logs server
          echo "=== Test logs ==="
          docker compose -f integration-tests.yml logs integration-tests

      - name: Cleanup
        if: always()
        run: docker compose -f integration-tests.yml down -v

      # Move cache to prevent it from growing indefinitely
      - name: Rotate cache - server
        if: always()
        run: |
          rm -rf /tmp/.buildx-cache-server
          mv /tmp/.buildx-cache-server-new /tmp/.buildx-cache-server || true

      - name: Rotate cache - tests
        if: always()
        run: |
          rm -rf /tmp/.buildx-cache-tests
          mv /tmp/.buildx-cache-tests-new /tmp/.buildx-cache-tests || true
